from pydantic import BaseModel, Field
from typing import List, Dict

class NetworkPacketInput(BaseModel):
    """
    The raw packet telemetry vector and system context sent by the network sensor hook.
    """
    features: Dict[str, float] = Field(
        ..., 
        description="A dictionary containing the 78 network flow features (e.g., 'Bwd IAT Max', 'Flow Bytes/s')"
    )
    current_system_load: float = Field(
        0.0, 
        description="The current utilization metrics of the active machine node"
    )

class DefenseDecisionResponse(BaseModel):
    """
    The multi-tier mitigation decision sent back to the firewall network controller.
    """
    packet_status: str = Field(..., description="Status of packet pipeline processing")
    tier1_primary_threat_class: str = Field(..., description="Threat classification assigned by Tier 1 LightGBM")
    tier2_anomaly_score: float = Field(..., description="Raw anomaly score generated by Tier 2 Isolation Forest")
    recommended_action: str = Field(..., description="Final optimized action decided by Tier 3 PPO Agent")
    action_code: int = Field(..., description="Numerical mapping of the recommended policy action")
    processing_latency_ms: float = Field(..., description="Total inference turnaround latency in milliseconds")

class FeatureContribution(BaseModel):
    """
    Represents an individual feature's absolute mathematical push 
    toward an attack classification or benign status.
    """
    feature: str = Field(..., description="The name of the network packet metric")
    value: float = Field(..., description="The actual raw or scaled numerical value parsed from the flow")
    shap_contribution: float = Field(..., description="The exact SHAP value allocation for this specific class target")
    direction: str = Field(..., description="Indicates if the value pushes 'toward_attack' or 'toward_benign'")

class PacketExplanationResponse(BaseModel):
    """
    The complete cryptographic-forensics payload returned to the threat analyst.
    """
    predicted_class: str = Field(..., description="The primary classification match assigned by Tier 1")
    confidence: float = Field(..., description="Probability matrix confidence score (0.0 to 1.0)")
    all_class_probs: Dict[str, float] = Field(..., description="Complete multi-class breakdown for cross-referencing anomalies")
    top_features: List[FeatureContribution] = Field(..., description="The top N features driving this localized prediction")
    verdict: str = Field(..., description="A clean, human-readable natural language summary of the threat indicators")